### ISSUE TITLE
Please mark mod as client side only.

### ISSUE THREAD

**Issue by Claycorp** [MrNerdy42/Keyboard-Wizard#1]
Mark the mod as client side only please, Thanks.

**Comment by MrNerdy42** [comment]
Do you mean in the description or the code itself? I can certainly put it in the readme, but there's no way that I know of to do it in code.

**Comment by Claycorp** [comment]
in your @mod you need to put @Side.CLIENT or something of the sorts, I don't have anything on hand to know exactly what it is. Then it won't load on servers and cause crashes making it easier to use and gives less issues for you.

**Comment by MrNerdy42** [comment]
Adding a @SideOnly(Side.CLIENT) annotation to the main mod class does not prevent the mod from being run on (and subsequently crashing) a server. I don't know of any other way prevent my code from running on a dedicated server.

**Comment by dries007** [comment]
Depending on the Forge version you can specify it in the Main Mod annotation, with `@Mod(clientSideOnly = true)` or, if that's not available, use the manifest by adding this to your build.gradle:
```gradle
jar {
    manifest {
        attributes 'ModSide': 'CLIENT'
    }
}
```

**Comment by MrNerdy42** [comment]
Thanks, `@Mod(clientSideOnly = true)` works perfectly.
