### ISSUE TITLE
[Feature] Show mod name in bindings list

### ISSUE THREAD

**Issue by Brycey92** [MrNerdy42/Keyboard-Wizard#10]
In addition to the control name and bound key, the left hand searchable list should also include the name of the mod that the control belongs to.

If this feature were to be added, I would love if it were added to 1.10.2!

**Comment by MrNerdy42** [comment]
I am no longer maintaining the 1.10.2 version of this mod. I'll consider it for 1.12.2 though.

**Comment by Brycey92** [comment]
Yeah, at this point you can disregard the request for 1.10.2, as I'm on 1.12.2 now anyway.

**Comment by MrNerdy42** [comment]
After looking into this, I've concluded that there's no way to figure out which mod a keybind comes from. I can only see its in-game category, which I already display.

**Comment by Brycey92** [comment]
That's fair. Would it be possible to show the category at least then?
