### ISSUE TITLE
[Feature] Arrow keys in keyboard wizard

### ISSUE THREAD

**Issue by LemmaEOF** [MrNerdy42/Keyboard-Wizard#11]
There aren't currently any arrow keys in the keyboard wizard menu, so you can't bind anything to them. They're helpful if you don't have a numpad and you need somewhere to bind more keys to, so could they be added in?

**Comment by MrNerdy42** [comment]
Sure, I don't see why not. I'm finally getting back to this project, so look for arrow keys in a release or two.

**Comment by ExcitedName** [comment]
I was just about to post the same request, lol.

**Comment by ariosos** [comment]
Has this been added somewhere? I was coming to request this, too.
