### ISSUE TITLE
Crash when searching "way"

### ISSUE THREAD

**Issue by Brycey92** [MrNerdy42/Keyboard-Wizard#12]
I searched "way" in the controls GUI with the UW Vanilla Enhanced+ modpack, and this happened: https://gist.github.com/Brycey92/27aa8ddcd96a34e7098ed856945ef554

**Comment by MrNerdy42** [comment]
#5 You're using an old version.
`| UCHIJA | keywizard               | 1.10.2-1.5                   | keywizard-1.12.2-1.5.2.jar `

**Comment by Brycey92** [comment]
Thanks!
