### ISSUE TITLE
[Feature] Search Box Toggle

### ISSUE THREAD

**Issue by pkej** [MrNerdy42/Keyboard-Wizard#13]
In the search box below the bindings list would it be possible to toggle the search to either search for function names (as it does today) and one for keybindings, i.e. let me get all bindings that use the letter and/or keyname, with or without modifier?

**Comment by MrNerdy42** [comment]
I'll consider it.

**Comment by MrNerdy42** [comment]
This functionality has been added! Check out the latest commit
