### ISSUE TITLE
Bindings not persistent after shutdown

### ISSUE THREAD

**Issue by ExcitedName** [MrNerdy42/Keyboard-Wizard#15]
Forge: 14.23.5.2768
Keyboard Wizard: 1.12.2-1.5.4
Issues with: SelimsBackpacks-1.12.2-1.1.3

To reproduce:
Change the key bind via the Keyboard Wizard GUI and click done. Quit game and close minecraft. Re-launch minecraft, key not bound.

**Comment by MrNerdy42** [comment]
I've confirmed that this bug persists in an environment without keyboard wizard installed, i.e. with the vanilla controls gui. This is either a Forge issue or an issue with Selim's Backpacks.

**Comment by ExcitedName** [comment]
Okay, thanks for looking into it.

**Comment by MrNerdy42** [comment]
Sure thing. I'm going to open up an issue on Selim's Backpacks
