### ISSUE TITLE
Reset Keybindings Issues

### ISSUE THREAD

**Issue by NielsPilgaard** [MrNerdy42/Keyboard-Wizard#16]
Hello o/

Several of my users have reported that it's far too easy to hit the reset keybindings button by accident - I would like it if you had to hold ctrl+shift+click or something similar, to avoid missclicks :)

**Comment by MrNerdy42** [comment]
Thanks for passing on the issue. I'm open to persuasion, but I don't think I'll fix this. I just don't see a reason why it should be easier to press than the "reset all" button in the vanilla controls gui.

**Comment by NielsPilgaard** [comment]
I think that button is too easy to push by accident as well, but I don't think I can request a change to vanilla :P
Oh well.

**Comment by MrNerdy42** [comment]
It's not entirely impossible, but I think it's out of the scope of the project :P Thanks again though!
