### ISSUE TITLE
[Request] Mouse 1 and mouse 2

### ISSUE THREAD

**Issue by MissPotato** [MrNerdy42/Keyboard-Wizard#17]
While both of these aren't exactly keyboard keys, it would be pretty convenient to have them on the page to allow applying to other keybindings or inverting left and right click.

**Comment by MrNerdy42** [comment]
I've been noodling around different ways to add mouse buttons and I think I'll start trying them out in the next few versions. Stay tuned!

**Comment by MrNerdy42** [comment]
Mouse buttons have been added! Check out the latest commit (build coming soon)
