### ISSUE TITLE
Search bar in the list

### ISSUE THREAD

**Issue by P3t3rU5** [MrNerdy42/Keyboard-Wizard#2]
A search bar in the list would be essential when you have lots of keybindings.

**Comment by MrNerdy42** [comment]
Checkout the upstream branch, I'm working on adding a NEI-like category selector. Not exactly what you are asking for, but it's a step in the right direction.

**Comment by MrNerdy42** [comment]
Just started a pull request for a search bar. Not much right now, but I'll continue to try and get it functioning.
