### ISSUE TITLE
Feature Request - Sort bindings

### ISSUE THREAD

**Issue by ariosos** [MrNerdy42/Keyboard-Wizard#20]
Above the keybindings listbox, it should have 3 buttons for sorting by Keybinding, Mod, and Key.

**Comment by MrNerdy42** [comment]
Sorting by mod is impossible and was addressed in #10. I'll consider the other two, however.

**Comment by MrNerdy42** [comment]
At long last, I added back end support for this in the latest commit. Look out for sorting in the next version.
