### ISSUE TITLE
Category list goes off screen

### ISSUE THREAD

**Issue by Notlucky101** [MrNerdy42/Keyboard-Wizard#21]
I just recently installed a mod back, and add keyboard wizard so I can of course configure the keys.
Slight problem I cannot see everything,  A slider or tab function might be appropriate . Normally I would not put that many mods in but hey I thought I will give it a try.
The Mod pack is Dungeons Dragons and space shuttle
![2019-08-16_05 07 16](https://user-images.githubusercontent.com/42447191/63166796-4a35cf80-bfe4-11e9-930b-64f9c7894679.png)

**Comment by MrNerdy42** [comment]
Woah I've never seen that many keybinding categories. This is definitely something I should look into, however.

**Comment by Notlucky101** [comment]
any luck in fixing that problem reported in Aug???

**Comment by MrNerdy42** [comment]
Pretty much everything I'm doing right now, school especially, takes priority over maintaining this project. My apologies for your having to wait.

**Comment by MrNerdy42** [comment]
Complete
