### ISSUE TITLE
Buggy with NoCtrl

### ISSUE THREAD

**Issue by ghost** [MrNerdy42/Keyboard-Wizard#26]
If both keyboard wizard and NoCtrl are used together, keyboard wizard doesn't save keybinds for each keyset in NoCtrl properly. The keys in each preset are overwritten.

NoCtrl: https://www.curseforge.com/minecraft/mc-mods/noctrl

**Comment by DoomRater** [comment]
We should try to rule out that it's not NoCtrl's fault first.  Seems there are more bugs in there than I thought at first with experimental code- no guarantee some of that isn't in the release version too.  And there are situations where NoCtrl will eat keys and redo actions it shouldn't.

**Comment by MrNerdy42** [comment]
> If both keyboard wizard and NoCtrl are used together, keyboard wizard doesn't save keybinds for each keyset in NoCtrl properly. The keys in each preset are overwritten.
> 
> NoCtrl: https://www.curseforge.com/minecraft/mc-mods/noctrl

If you could provide specific steps to reproduce this issue, as well as log files collected while reproducing the issue I could begin to look into this when I get back to development later this year.

**Comment by MrNerdy42** [comment]
Closing due to lack of response and new direction of mod.
