### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by Sean2739** [MrNerdy42/Keyboard-Wizard#27]
This isnt really an issue but more of a suggestion, please, please, PLEASE, port to 1.8.9 forge, currently the only mod similar to this is controlling and the older ports are very buggy & this would seem like a reallly cool additions to forge modpacks and pvp clients alike.

**Comment by MrNerdy42** [comment]
I'm not affiliated with the project, but check out Keyboard Wizard Legacy by mikhailtapio

https://www.curseforge.com/minecraft/mc-mods/keyboard-wizard-legacy
