### ISSUE TITLE
[1.12.1] Crash opening the Controls menu

### ISSUE THREAD

**Issue by MokahTGS** [MrNerdy42/Keyboard-Wizard#3]
Getting an odd crash when trying to open the controls menu on 1.12.1

https://pastebin.com/q1impHDg

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/357 Smae issue. If only keyWiz and FUutrepack are put together it crashes with a IndexOutOfBound exception. Why is that so? I register the keybindings the same way JEI does, do I have to do it at a certain point in time ?

**Comment by P3rf3ctXZer0** [comment]
@Thutmose didn't you fix a bug like this for me back in 1.7.10?

**Comment by MrNerdy42** [comment]
I picked the wrong time to disappear for a while. It seems like it was confirmed that there is definitely a conflict between KeyboardWizard and the Futurepack Mod. @mcenderdragon could you point me to your key binding code? It would help me get an idea of how our mods interact.

**Comment by mcenderdragon** [comment]
I think by now this issue should be resolved. So a test with the latest version for 1.12.2 is needed.

**Comment by MrNerdy42** [comment]
Great! I wasn't aware this was already addressed. I'll test it out this evening.

**Comment by MrNerdy42** [comment]
Okay so I've tested keyWiz and futurepack together and there was no smoke. I'm going to check this one off my list.
