### ISSUE TITLE
Request - Functioon keys

### ISSUE THREAD

**Issue by charlesbevans** [MrNerdy42/Keyboard-Wizard#4]
Extra keys can vary by computer, but function keys are a given.

**Comment by MrNerdy42** [comment]
Out of all the issues, this one is actually the hardest to implement besides support for international keyboards. This is also on the back burner, but not totally ruled out.

**Comment by charlesbevans** [comment]
Understood. Thanks for considering it. Out of curiosity, what makes it so difficult?

**Comment by MrNerdy42** [comment]
Honestly the difficulty comes mostly from my desire to implement it elegantly. Currently lwgjl returns null when you call getKeyName(int id) with the id of a function key. The only way I can think of adding 12 new cases to my already messy switch statement that decodes key names, which kinda feels like a hack to me. I may end up creating a new method specifically for placing the function keys, but we'll see.

**Comment by MrNerdy42** [comment]
I'll amend my last comment by saying that it looks like you are indeed running the full release (1.5.3), but I downloaded your modpack on Technic and experienced the same bug you did. When I looked at the version of keyboard wizard, it was the beta. I don't really know what to make of this.
