### ISSUE TITLE
Does not save

### ISSUE THREAD

**Issue by torenne** [MrNerdy42/Keyboard-Wizard#4]
It seems to me that the new key settings does not save, and have to be configured every time the game loads. Is it possible to add a "Save" button?

**Comment by Adarcer** [comment]
You need to open menu and go into controls and then just exit too save. I actually think this is good just in case you mess up badly :P

**Comment by Brycey92** [comment]
This isn't a feature, this is a bug, and it causes unnecessary frustration with users of the mod. That being said, this issue is still present in 1.5.2 for MC 1.12.2.

**Comment by ghost** [comment]
Ran into this today. The default keybinding to access this mod conflicts with moreoverlays. I'm going to remove this from my pack because, as nice as it is, it's obvious this isn't getting fixed anytime soon.

**Comment by MrNerdy42** [comment]
This is definitely a pretty serious issue. I'll look into it now that I finally have time to maintain this thing.

**Comment by Brycey92** [comment]
This bug is still present in the latest release (1.5.3). @MrNerdy42, please reopen this issue.

**Comment by MrNerdy42** [comment]
I tested this before releasing and again just before replying to you. I am unable to reproduce this behavior in version 1.5.3. May I see your mod list, and log files?

**Comment by Brycey92** [comment]
Mod list: [dir.txt](https://github.com/MrNerdy42/Keyboard-Wizard/files/2757192/dir.txt)

Logs: [logs.zip](https://github.com/MrNerdy42/Keyboard-Wizard/files/2757261/logs.zip)
The logs inside gz files are from the first run, where the keybinds were changed, and the changes persisted through the session. The logs in the root of the zip file are from the second run, where the keybinds had reverted to their previous values.

Launcher log, if you need it: [techniclauncher_2019-01-14.log](https://github.com/MrNerdy42/Keyboard-Wizard/files/2757263/techniclauncher_2019-01-14.log)
This contains the launcher log for both runs.

**Comment by MrNerdy42** [comment]
Sorry I took two days to respond. Your problem is that Galaxy-Craft Lite is still using the beta (1.5.3-b1), the bug wasn't fixed until the full release of 1.5.3.

**Comment by Brycey92** [comment]
I'm actively making the next version of the pack, so I was trying to test the updated mods before I released the pack update.

Oddly enough, I just tried again with different keys, and they were saved this time. I'll let you know when I get the pack update out so you can test it.

**Comment by MrNerdy42** [comment]
Perfect. In the meantime, I'll keep testing different combinations of mods and configs to see if I can recreate your issue.

**Comment by Brycey92** [comment]
It may be useful to know that the keys I tried changing the first time (which didn't stick) involved unbinding the scene related keys from the numpad. In the second attempt, which did work, I think I was changing the keys for some mod's functions.

**Comment by MrNerdy42** [comment]
Could you point me to the mod that does this? If not I can take a look at it next time have access to my dev environment.

**Comment by Brycey92** [comment]
I think the scene keys were from vanilla Minecraft, but I don't remember which mod's keys I changed. [Here](https://www.technicpack.net/modpack/galaxy-craft-modpack.210706)'s the modpack I'm using. I released the update for it tat I was talking about.

**Comment by MrNerdy42** [comment]
Okay, I'm closing this issue. By scene keys I assume you mean these:
 ```
key_Scene1 start/pause:41
key_Scene2 start/pause:0
key_Scene3 start/pause:0
key_Scene reset:0
```
I am completely unable to reproduce the behavior you're seeing in 1.12.2-1.5.3. [This](https://www.youtube.com/watch?v=7bSyqJ7_uPc) is a video of these keys saving in the options.txt.

(As a side note I can't for the life of me figure out what these keys do or what mod they come from)
