### ISSUE TITLE
Separate GUI Scale or Changes to Scaling

### ISSUE THREAD

**Issue by Brycey92** [MrNerdy42/Keyboard-Wizard#7]
When Minecraft is fullscreened to 1080p, most mods' GUIs work fine, except Keyboard Wizard's GUI scales too far and goes off the edge of the screen. Would it be possible to either have a separate GUI scale option within the F7 GUI, or cap the scaling when listening to Minecraft's GUI Scale setting so that everything fits on the screen? Thanks!

**Comment by ElvenChaos** [comment]
Also an issue in 1.12.2.

**Comment by MrNerdy42** [comment]
At long last I may have found a way to fix this issue. I am going to be changing to a custom keyboard gui instead of using the vanilla buttons, which will hopefully give me more control over the size of the gui. Fingers crossed.

**Comment by MrNerdy42** [comment]
Check out the new beta to take a look at my solution to this issue (finally)

**Comment by Brycey92** [comment]
I'll take a look soon, thanks!
