### ISSUE TITLE
[Feature] More keys

### ISSUE THREAD

**Issue by Brycey92** [MrNerdy42/Keyboard-Wizard#8]
I hereby request the addition of more keyboard keys, specifically insert, delete, home, end, page up, page down, arrow keys, numpad /, numpad +, numpad *, numpad enter, numpad -, print screen, and pause/break.

If this feature were to be added, I would love if it were added to 1.10.2!

**Comment by MrNerdy42** [comment]
I'll file this with the request for arrow keys.

**Comment by Brycey92** [comment]
Disregard request for 1.10.2 support.

**Comment by pkej** [comment]
And I would like to add for function keys f13 to f24 :) Even if they're not on my keyboard, I can bind them to my Stream Deck, or to other keyboards with autohotkey :)

**Comment by MrNerdy42** [comment]
Still considering this, but I'm going to close the issue for maintenance reasons.

**Comment by Brycey92** [comment]
Why close the issue if you're still considering it? Unless you have a master list of planned features somewhere?

**Comment by MrNerdy42** [comment]
It's fallen so low on my priority list that it is essentially stale. I will reopen when I actually intend to address it.
